version: "3.9"

secrets:
  pg_n8n_pass:
    external: true
  n8n_encryption_key:
    external: true
  n8n_user_mgmt_jwt_secret:
    external: true

networks:
  public:
    external: true
  internal:
    external: true

services:
  n8n:
    image: n8nio/n8n:1
    user: "1000:1000"

    environment:
      - GENERIC_TIMEZONE=America/Bogota

      # Public URL (Traefik)
      - N8N_HOST=n8n.sexydad
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.sexydad/

      # DB (Postgres)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres_postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD_FILE=/run/secrets/pg_n8n_pass

      # Sensitive (via secrets files)
      - N8N_ENCRYPTION_KEY_FILE=/run/secrets/n8n_encryption_key
      - N8N_USER_MANAGEMENT_JWT_SECRET_FILE=/run/secrets/n8n_user_mgmt_jwt_secret

      # Optional hardening
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false

    volumes:
      - /srv/fastdata/n8n:/home/node/.n8n

    secrets:
      - pg_n8n_pass
      - n8n_encryption_key
      - n8n_user_mgmt_jwt_secret

    networks:
      - internal
      - public

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == master2
          - node.labels.tier == compute
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.n8n.rule=Host(`n8n.sexydad`)
        - traefik.http.routers.n8n.entrypoints=websecure
        - traefik.http.routers.n8n.tls=true
        - traefik.http.routers.n8n.middlewares=lan-whitelist@docker
        - traefik.http.services.n8n.loadbalancer.server.port=5678
