version: "3.9"

networks:
  public:
    external: true
  internal:
    external: true

services:
  agent:
    image: portainer/agent:2.21.0
    networks:
      - internal
    deploy:
      mode: global
      restart_policy:
        condition: any
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

  portainer:
    image: portainer/portainer-ce:2.21.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - public
      - internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.tier == control
      restart_policy:
        condition: any
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.portainer.rule=Host(`portainer.sexydad`)
        - traefik.http.routers.portainer.entrypoints=websecure
        - traefik.http.routers.portainer.tls=true
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - traefik.http.routers.portainer.middlewares=lan-whitelist@docker
    volumes:
      - /srv/portainer/data:/data
