version: "3.9"

services:
  jupyter_ogiovanni:
    image: jupyter/datascience-notebook:python-3.11
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS='-R'
    volumes:
      - /srv/fastdata/jupyter/ogiovanni:/home/jovyan/work
    networks:
      - public
      - internal
    command: >
      start-notebook.sh
      --ServerApp.ip=0.0.0.0
      --ServerApp.port=8888
      --ServerApp.token=''
      --ServerApp.password=''
      --ServerApp.allow_remote_access=True
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == master2
          - node.labels.tier == compute
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.jupyter-ogiovanni.rule=Host(`jupyter-ogiovanni.sexydad`)
        - traefik.http.routers.jupyter-ogiovanni.entrypoints=websecure
        - traefik.http.routers.jupyter-ogiovanni.tls=true
        - traefik.http.routers.jupyter-ogiovanni.middlewares=jupyter-chain@docker
        - traefik.http.services.jupyter-ogiovanni.loadbalancer.server.port=8888

  jupyter_odavid:
    image: jupyter/datascience-notebook:python-3.11
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS='-R'
    volumes:
      - /srv/fastdata/jupyter/odavid:/home/jovyan/work
    networks:
      - public
      - internal
    command: >
      start-notebook.sh
      --ServerApp.ip=0.0.0.0
      --ServerApp.port=8888
      --ServerApp.token=''
      --ServerApp.password=''
      --ServerApp.allow_remote_access=True
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == master2
          - node.labels.tier == compute
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.jupyter-odavid.rule=Host(`jupyter-odavid.sexydad`)
        - traefik.http.routers.jupyter-odavid.entrypoints=websecure
        - traefik.http.routers.jupyter-odavid.tls=true
        - traefik.http.routers.jupyter-odavid.middlewares=jupyter-chain@docker
        - traefik.http.services.jupyter-odavid.loadbalancer.server.port=8888

networks:
  public:
    external: true
  internal:
    external: true