version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_super_pass
      POSTGRES_DB: n8n
    secrets:
      - pg_super_pass
      - pg_n8n_pass
    configs:
      - source: init_n8n
        target: /docker-entrypoint-initdb.d/01-init-n8n.sh
        mode: 0555
    volumes:
      - /srv/fastdata/postgres:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      # IMPORTANTE: host mode para que solo abra en master2 (no routing mesh)
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          # usa la label que ya vienes manejando; ejemplo:
          - node.hostname == master2
          # alternativo (si tu plan está con labels):
          # - node.labels.storage == primary
      restart_policy:
            condition: any
            delay: 5s
            max_attempts: 0
            window: 60s

networks:
  internal:
    external: true

secrets:
  pg_super_pass:
    external: true
  pg_n8n_pass:
    external: true

configs:
  init_n8n:
    file: ./initdb/01-init-n8n.sh
