"""
LangGraph Hybrid Agent — State definition.

The AgentState is the single source of truth that flows through every node.
LangGraph passes it immutably — each node returns a dict with ONLY the fields it updates.
"""

from typing import TypedDict


class AgentState(TypedDict):
    """State shared across all nodes in the agent graph."""

    # Input
    question: str
    session_id: str

    # Routing decision made by the Router node
    # Values: "rag" | "data" | "both"
    route: str

    # RAG Tool output
    rag_chunks: list[dict]  # [{"filename": ..., "chunk_text": ..., "score": ...}]
    rag_context: str  # formatted context string for the LLM

    # Data Tool output
    sql_query: str  # SQL generated by qwen2.5-coder
    sql_result: list[dict]  # rows returned from Postgres
    data_context: str  # formatted data string for the LLM

    # Final answer
    answer: str

    # Observability — written to OpenSearch at the end
    tool_used: str  # "rag" | "data" | "both"
    latency_ms: float
    model: str
    chunks_retrieved: int
